### ISSUE TITLE
Thread - Demo Programs have threading design patterns.... added a new Trinket one.

### ISSUE THREAD

**Issue by PySimpleGUI** [villares/sketch-a-day#2]
pip install psgdemos

Run the demo browser and search (F2) for stuff like start_thread or long_operation

![image](https://user-images.githubusercontent.com/46163555/201307340-035b57f3-79c6-4149-89f4-ee5c150a8832.png)

You cannot make a PySimpleGUI call from a thread... the one exception is `write_event_value` which enables you to inject an event into a window's event loop.

I added this trinket that may help you see the latest way I do threading.

https://pysimplegui.trinket.io/demo-programs#/multi-threaded/multi-threaded-download-2022-design-pattern

**Comment by villares** [comment]
Thanks!
